name: $(BuildID)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

resources:
  repositories:
  - repository: azure-iot-dde
    type: git
    endpoint: msazure
    name: One/azure-iot-dde

trigger: 
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - doc/*

jobs:
- job: NXP_Build
  pool:
    name: 'IoT-DDE-Device-Lab'
    demands:
    - NXPMIMXRT1060EVK -equals true
  steps:
  - checkout: self
    clean: true
    submodules: recursive
  - checkout: azure-iot-dde
    clean: true

  # Azure CLI to start certification
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'IoT-DDE-team-subscription'
      scriptType: 'ps'
      scriptLocation: 'scriptPath'
      scriptPath: '$(Build.SourcesDirectory)\azure-iot-dde\generate_creds.ps1'
      arguments: '$(Build.SourcesDirectory)\getting-started\core\model'
      useGlobalConfig: true
    displayName: "Start Certification"

  # modify config with credentials 
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: '$(Build.SourcesDirectory)\azure-iot-dde\update_config.ps1'
      arguments: > # Use this to avoid newline characters in multiline string
        -ConfigFilePath '$(Build.SourcesDirectory)\getting-started\NXP\MIMXRT1060-EVK\app\azure_config.h'
    displayName: 'Modify config file'

  # Build binary
  - script: |
      echo %PATH%
      cd $(Build.SourcesDirectory)\getting-started\NXP\MIMXRT1060-EVK\tools
      .\rebuild.bat
    displayName: "Build Binary"

  # Flash binary to hardware
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: '$(Build.SourcesDirectory)\azure-iot-dde\flashing_tools\flash-board.ps1'
      arguments: > # Use this to avoid newline characters in multiline string
        -BinPath '$(Build.SourcesDirectory)\getting-started\NXP\MIMXRT1060-EVK\build\app\mimxrt1060_azure_iot.hex'
    displayName: 'Flash binary'

  # Monitor device for successful connection to Iot Hub
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: '$(Build.SourcesDirectory)\azure-iot-dde\scan_serial.ps1'
      arguments: > # Use this to avoid newline characters in multiline string
        -TestString 'SUCCESS: Azure IoT Hub client initialized'
    displayName: 'Scan serial port'

  # Azure CLI to run certification
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'IoT-DDE-team-subscription'
      scriptType: 'ps'
      scriptLocation: 'scriptPath'
      scriptPath: '$(Build.SourcesDirectory)\azure-iot-dde\run_certification.ps1'
      arguments: $(TESTID)
      useGlobalConfig: true
    displayName: "Run Certification"
