name: ATSAME54-XPRO

on:
  push:
    branches: [ master ]
    paths:
      - 'common/**'
      - 'cmake/**'
      - 'Microchip/ATSAME54-XPRO/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'common/**'
      - 'cmake/**'
      - 'Microchip/ATSAME54-XPRO/**'

defaults:
  run:
    working-directory: Microchip/ATSAME54-XPRO

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Get the ARM GCC compiler
      - name: Install arm-none-eabi-gcc
        uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: '9-2019-q4'

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build project
        run: |
          cmake -Bbuild -GNinja -DCMAKE_TOOLCHAIN_FILE="../../cmake/arm-gcc-cortex-m4.cmake" 
          cmake --build build
