name: B-L475E-IOT01A

on:
  push:
    branches: [ master ]
    paths:
      - 'common/**'
      - 'cmake/**'
      - 'STMicroelectronics/B-L475E-IOT01A/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'common/**'
      - 'cmake/**'
      - 'STMicroelectronics/B-L475E-IOT01A/**'

defaults:
  run:
    working-directory: STMicroelectronics/B-L475E-IOT01A

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Get the ARM GCC compiler
      - name: Install arm-none-eabi-gcc
        uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: '9-2019-q4'

      - name: Install cmake
        uses: lukka/get-cmake@v3.17.1

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v1

      - name: Build project
        run: |
          cmake -Bbuild -GNinja -DCMAKE_TOOLCHAIN_FILE="../../cmake/arm-gcc-cortex-m4.cmake" 
          cmake --build build
          