name: B-L475E-IOT01A

on:
  push:
    branches: [ master ]
    paths:
      - 'common/**'
      - 'cmake/**'
      - 'STMicroelectronics/B-L475E-IOT01A/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'common/**'
      - 'cmake/**'
      - 'STMicroelectronics/B-L475E-IOT01A/**'

defaults:
  run:
    working-directory: STMicroelectronics/B-L475E-IOT01A

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install arm-none-eabi-gcc
        uses: fiam/arm-none-eabi-gcc@v1
        if: steps.cache-arm-gcc.outputs.cache-hit != 'true'
        with:
          release: '9-2019-q4'
          directory: $HOME/arm-none-eabi-gcc-9-2019-q4

      - name: Build project
        env:
          ARM_GCC_PATH: "$HOME/arm-none-eabi-gcc-9-2019-q4/bin"
        run: |
          cmake -Bbuild -GNinja -DCMAKE_TOOLCHAIN_FILE="../../cmake/arm-gcc-cortex-m4.cmake" 
          cmake --build build
