name: cache-update

on:
  schedule:
    - cron: '0 0 */3 * *' # every 30m for testing

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:    
    # Cache location for arm tools
    - name: Cache arm-none-eabi-gcc tools
      uses: actions/cache@v1
      with:
        path: ~/arm-none-eabi-gcc-9-2019-q4
        key: ${{ runner.os }}-arm-gcc-9-2019-q4

    # Get the arm-non-eabi-gcc toolchain   
    - name: Install arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
          release: '9-2019-q4'
          directory: ~/arm-none-eabi-gcc-9-2019-q4