name: MIMXRT1060-EVK

on:
  push:
    branches: [ master ]
    paths:
      - 'common/**'
      - 'cmake/**'
      - 'NXP/MIMXRT106-EVK/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'common/**'
      - 'cmake/**'
      - 'NXP/MIMXRT106-EVK/**'

defaults:
  run:
    working-directory: NXP/MIMXRT106-EVK

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: seanmiddleditch/gha-setup-ninja@master

      - uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: '9-2019-q4'

      - name: Build project
        run: |
          cmake -Bbuild -GNinja -DCMAKE_TOOLCHAIN_FILE="../../cmake/arm-gcc-cortex-m7.cmake" 
          cmake --build build
